### ISSUE TITLE
World tries to load, then dies...

### ISSUE THREAD

**Issue by therealericbj** [iconmaster5326/AetherCraft#31]
I try to startup my dedicated server and this happens...

ForgeMicroblock{1.1.0.307} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.307-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    asielibcore{} [AsieLib CoreMod](minecraft.jar) Unloaded->Disabled
[23:58:30] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[23:58:30] [Server thread/ERROR] [FML/]: Caught exception from AetherCraft
java.lang.StackOverflowError
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:215) ~[add.class:?]
    at com.iconmaster.aec.util.UidUtils.getUID(UidUtils.java:21) ~[UidUtils.class:?]
    at com.iconmaster.aec.aether.AVRegistry.isHardcoded(AVRegistry.java:120) ~[AVRegistry.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getItemAV(DynamicAVRegister.java:110) ~[DynamicAVRegister.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getRecipeAV(DynamicAVRegister.java:158) ~[DynamicAVRegister.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getItemAV(DynamicAVRegister.java:120) ~[DynamicAVRegister.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getRecipeAV(DynamicAVRegister.java:158) ~[DynamicAVRegister.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getItemAV(DynamicAVRegister.java:120) ~[DynamicAVRegister.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getRecipeAV(DynamicAVRegister.java:158) ~[DynamicAVRegister.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getItemAV(DynamicAVRegister.java:120) ~[DynamicAVRegister.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getRecipeAV(DynamicAVRegister.java:158) ~[DynamicAVRegister.class:?]

This goes on for a while, then this happens...

at com.iconmaster.aec.aether.DynamicAVRegister.getItemAV(DynamicAVRegister.java:120) ~[DynamicAVRegister.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getRecipeAV(DynamicAVRegister.java:158) ~[DynamicAVRegister.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getItemAV(DynamicAVRegister.java:120) ~[DynamicAVRegister.class:?]
[23:58:30] [Server thread/ERROR] [FML/]: A fatal exception occurred during the server starting event
cpw.mods.fml.common.LoaderException: java.lang.StackOverflowError
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162) ~[LoadController.class:?]
    at cpw.mods.fml.common.Loader.serverStarting(Loader.java:740) [Loader.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:278) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.StackOverflowError
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:215) ~[add.class:?]
    at com.iconmaster.aec.util.UidUtils.getUID(UidUtils.java:21) ~[UidUtils.class:?]
    at com.iconmaster.aec.aether.AVRegistry.isHardcoded(AVRegistry.java:120) ~[AVRegistry.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getItemAV(DynamicAVRegister.java:110) ~[DynamicAVRegister.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getRecipeAV(DynamicAVRegister.java:158) ~[DynamicAVRegister.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getItemAV(DynamicAVRegister.java:120) ~[DynamicAVRegister.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getRecipeAV(DynamicAVRegister.java:158) ~[DynamicAVRegister.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getItemAV(DynamicAVRegister.java:120) ~[DynamicAVRegister.class:?]
    at com.iconmaster.aec.aether.DynamicAVRegister.getRecipeAV(DynamicAVRegister.java:158) ~[DynamicAVRegister.class:?]

This goes on for a while again, then everything seems to die and ends up with this...

[23:58:31] [Server thread/TRACE] [denseores/denseores]: Sending event FMLServerStoppedEvent to mod denseores
[23:58:31] [Server thread/TRACE] [denseores/denseores]: Sent event FMLServerStoppedEvent to mod denseores
[23:58:31] [Server thread/TRACE] [ForgeMicroblock/ForgeMicroblock]: Sending event FMLServerStoppedEvent to mod ForgeMicroblock
[23:58:31] [Server thread/TRACE] [ForgeMicroblock/ForgeMicroblock]: Sent event FMLServerStoppedEvent to mod ForgeMicroblock
[23:58:31] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[23:58:31] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

There doesn't seem to be a crash report created, so all I have is the FML log and it's pretty big( 5.9 MB).  I have a zipped copy, if you want it please tell me how to get it to you.

Thanks

**Comment by smito** [comment]
Did you ever get an answer?

**Comment by therealericbj** [comment]
...nope.

**Comment by hughbe** [comment]
I am trying to use AetherCraft with FTB infinity, and get this error so I can't use the mod! Can we pleas have a fix for this?

**Comment by minecraftmodding1224** [comment]
if you ever get a fix for this,plz type here,facing same problem,had to take the mod out,very sad.
